# Garante que tudo que n8n salva em /data aparece na sua pasta ./data local
version: "3.7"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=senha123
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - TZ=America/Sao_Paulo
    volumes:
      - ./data:/data
      - ./scripts:/scripts

  python:
    build:
      context: ./python
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    working_dir: /scripts/python
    container_name: python-executor